# Generated by Django 6.0 on 2026-01-01 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('NGO', 'NGO'), ('DONOR', 'Donor')], default='DONOR', max_length=10),
        ),
    ]
