# Generated by Django 6.0 on 2025-12-10 15:09

import donations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_donation_approved_by_ngo_donation_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=donations.models.donation_image_upload_path),
        ),
    ]
