# Generated by Django 6.0 on 2025-12-23 00:56

import django.db.models.deletion
import donations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_alter_donation_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='guest_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='guest_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DonationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('blood', 'Blood Donation'), ('organ', 'Organ Donation'), ('money', 'Financial Donation'), ('food', 'Food Donation'), ('adahi', 'Adahi (Sacrifice)'), ('clothes', 'Clothes Donation'), ('furniture', 'Furniture Donation'), ('medical', 'Medical Equipment'), ('household', 'Household Items'), ('water', 'Clean Water'), ('baby', 'Baby Supplies'), ('toys', 'Toys Donation'), ('education', 'Education Support'), ('electronics', 'Electronics'), ('cleaning', 'Cleaning Supplies'), ('medicine_support', 'Medicine Support'), ('pets', 'Pet Support & Adoption'), ('volunteer', 'Volunteer Time'), ('skills', 'Professional Help'), ('families', 'Family Support'), ('refugees', 'Refugee Support'), ('orphans', 'Orphan Sponsorship'), ('charity_general', 'General Charity'), ('food_coupons', 'Food Coupons')], max_length=50)),
                ('description', models.TextField()),
                ('proof_document', models.FileField(blank=True, null=True, upload_to=donations.models.proof_upload_path)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
