export const categories = [
    { name: "Blood Donation", icon: "🩸", path: "/blood", color: "from-red-600 to-red-900" },
    { name: "Organ Donation", icon: "🫀", path: "/organ", color: "from-rose-600 to-rose-900" },
    { name: "Financial Donation", icon: "💵", path: "/money", color: "from-green-600 to-green-900" },
    { name: "Food Donation", icon: "🍱", path: "/food", color: "from-orange-500 to-yellow-600" },
    { name: "Adahi (Sacrifice)", icon: "🐑", path: "/adahi", color: "from-yellow-500 to-amber-600" },
    { name: "Clothes Donation", icon: "👕", path: "/clothes", color: "from-indigo-600 to-blue-800" },
    { name: "Furniture Donation", icon: "🛋️", path: "/furniture", color: "from-amber-700 to-orange-900" },
    { name: "Medical Equipment", icon: "🏥", path: "/medical", color: "from-teal-500 to-emerald-700" },
    { name: "Household Items", icon: "🏠", path: "/household", color: "from-slate-600 to-gray-800" },
    { name: "Clean Water", icon: "🚰", path: "/water", color: "from-cyan-500 to-blue-600" },
    { name: "Baby Supplies", icon: "🍼", path: "/baby", color: "from-pink-400 to-rose-600" },
    { name: "Toys Donation", icon: "🧸", path: "/toys", color: "from-orange-400 to-red-500" },
    { name: "Education Support", icon: "🎒", path: "/education", color: "from-blue-600 to-indigo-800" },
    { name: "Electronics", icon: "📱", path: "/electronics", color: "from-indigo-500 to-purple-700" },
    { name: "Cleaning Supplies", icon: "🧼", path: "/cleaning", color: "from-lime-500 to-green-700" },
    { name: "Medicine Support", icon: "💊", path: "/medicine-support", color: "from-purple-600 to-fuchsia-800" },
    { name: "Pet Support", icon: "🐾", path: "/pets", color: "from-stone-500 to-neutral-700" },
    { name: "Volunteer Time", icon: "⏳", path: "/volunteer", color: "from-gray-500 to-slate-700" },
    { name: "Professional Help", icon: "🛠️", path: "/skills", color: "from-yellow-600 to-amber-800" },
    { name: "Family Support", icon: "👨‍👩‍👧‍👦", path: "/families", color: "from-rose-500 to-pink-700" },
    { name: "Refugee Support", icon: "🛂", path: "/refugees", color: "from-sky-500 to-blue-700" },
    { name: "Orphan Sponsorship", icon: "🤝", path: "/orphans", color: "from-green-500 to-emerald-700" },
    { name: "General Charity", icon: "🤲", path: "/charity-general", color: "from-violet-600 to-indigo-800" },
    { name: "Food Coupons", icon: "🎟️", path: "/food-coupons", color: "from-fuchsia-500 to-purple-700" },
];
